apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp_test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp_test
  template:
    metadata:
      labels:
        app: nodeapp_test 
    spec:
      containers:
      - name: nodeserver
        image: adizura007/nodeapp_test:latest
        ports:
        - containerPort: 3000
